<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/JianYe.proto

namespace Sample\Model\GPBMetadata\Proto;

class JianYe
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aca010a1270726f746f2f4a69616e59652e70726f746f120c53616d706c" .
            "652e4d6f64656c222d0a07416c6c496e666f12220a04696e666f18012003" .
            "280b32142e53616d706c652e4d6f64656c2e4a69616e5965226f0a064a69" .
            "616e5965120c0a046461746518012001280912100a08746f74616c517479" .
            "18022001280d12120a0a63757272656e7451747918032001280d12100a08" .
            "6f7264657251747918042001280d120f0a076c6f636b5174791805200128" .
            "0d120e0a0675736551747918062001280d620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}