<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/JianYe.proto

namespace Sample\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Sample.Model.JianYe</code>
 */
class JianYe extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>string date = 1;</code>
     */
    private $date = '';
    /**
     * <pre>
     *总库存
     * </pre>
     *
     * <code>uint32 totalQty = 2;</code>
     */
    private $totalQty = 0;
    /**
     * <code>uint32 currentQty = 3;</code>
     */
    private $currentQty = 0;
    /**
     * <code>uint32 orderQty = 4;</code>
     */
    private $orderQty = 0;
    /**
     * <code>uint32 lockQty = 5;</code>
     */
    private $lockQty = 0;
    /**
     * <code>uint32 useQty = 6;</code>
     */
    private $useQty = 0;

    public function __construct() {
        \Sample\Model\GPBMetadata\Proto\JianYe::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>string date = 1;</code>
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * <pre>
     *日期
     * </pre>
     *
     * <code>string date = 1;</code>
     */
    public function setDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->date = $var;
    }

    /**
     * <pre>
     *总库存
     * </pre>
     *
     * <code>uint32 totalQty = 2;</code>
     */
    public function getTotalQty()
    {
        return $this->totalQty;
    }

    /**
     * <pre>
     *总库存
     * </pre>
     *
     * <code>uint32 totalQty = 2;</code>
     */
    public function setTotalQty($var)
    {
        GPBUtil::checkUint32($var);
        $this->totalQty = $var;
    }

    /**
     * <code>uint32 currentQty = 3;</code>
     */
    public function getCurrentQty()
    {
        return $this->currentQty;
    }

    /**
     * <code>uint32 currentQty = 3;</code>
     */
    public function setCurrentQty($var)
    {
        GPBUtil::checkUint32($var);
        $this->currentQty = $var;
    }

    /**
     * <code>uint32 orderQty = 4;</code>
     */
    public function getOrderQty()
    {
        return $this->orderQty;
    }

    /**
     * <code>uint32 orderQty = 4;</code>
     */
    public function setOrderQty($var)
    {
        GPBUtil::checkUint32($var);
        $this->orderQty = $var;
    }

    /**
     * <code>uint32 lockQty = 5;</code>
     */
    public function getLockQty()
    {
        return $this->lockQty;
    }

    /**
     * <code>uint32 lockQty = 5;</code>
     */
    public function setLockQty($var)
    {
        GPBUtil::checkUint32($var);
        $this->lockQty = $var;
    }

    /**
     * <code>uint32 useQty = 6;</code>
     */
    public function getUseQty()
    {
        return $this->useQty;
    }

    /**
     * <code>uint32 useQty = 6;</code>
     */
    public function setUseQty($var)
    {
        GPBUtil::checkUint32($var);
        $this->useQty = $var;
    }

}