<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/User.proto

namespace Sample\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Sample.Model.User</code>
 */
class User extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *主键id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    private $id = 0;
    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    private $name = '';
    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    private $avatar = '';
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    private $address = '';
    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    private $mobile = '';
    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    private $ext;

    public function __construct() {
        \Sample\Model\GPBMetadata\Proto\User::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *主键id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * <pre>
     *主键id
     * </pre>
     *
     * <code>int64 id = 1;</code>
     */
    public function setId($var)
    {
        GPBUtil::checkInt64($var);
        $this->id = $var;
    }

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * <pre>
     *用户名
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;
    }

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * <pre>
     *头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;
    }

    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>string address = 4;</code>
     */
    public function setAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->address = $var;
    }

    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * <pre>
     *手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;
    }

    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    public function getExt()
    {
        return $this->ext;
    }

    /**
     * <pre>
     *扩展信息
     * </pre>
     *
     * <code>map&lt;string, string&gt; ext = 6;</code>
     */
    public function setExt(&$var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->ext = $arr;
    }

}

