<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/User.proto

namespace Sample\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Sample.Model.UserList</code>
 */
class UserList extends \Google\Protobuf\Internal\Message
{
    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    private $list;
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     * <pre>
     *分页条数
     * </pre>
     *
     * <code>int32 limit = 3;</code>
     */
    private $limit = 0;

    public function __construct() {
        \GPBMetadata\Proto\User::initOnce();
        parent::__construct();
    }

    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     * <pre>
     *用户列表
     * </pre>
     *
     * <code>repeated .Sample.Model.User list = 1;</code>
     */
    public function setList(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sample\Model\User::class);
        $this->list = $arr;
    }

    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>int32 page = 2;</code>
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>int32 page = 2;</code>
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;
    }

    /**
     * <pre>
     *分页条数
     * </pre>
     *
     * <code>int32 limit = 3;</code>
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     * <pre>
     *分页条数
     * </pre>
     *
     * <code>int32 limit = 3;</code>
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;
    }

}

