<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/User.proto

namespace GPBMetadata\Proto;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9d020a1070726f746f2f557365722e70726f746f120c53616d706c652e" .
            "4d6f64656c22a7010a0455736572120a0a026964180120012803120c0a04" .
            "6e616d65180220012809120e0a06617661746172180320012809120f0a07" .
            "61646472657373180420012809120e0a066d6f62696c6518052001280912" .
            "280a0365787418062003280b321b2e53616d706c652e4d6f64656c2e5573" .
            "65722e457874456e7472791a2a0a08457874456e747279120b0a036b6579" .
            "180120012809120d0a0576616c75651802200128093a02380122490a0855" .
            "7365724c69737412200a046c69737418012003280b32122e53616d706c65" .
            "2e4d6f64656c2e55736572120c0a0470616765180220012805120d0a056c" .
            "696d6974180320012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

